README.md

Add a note for EU and US regions when setting end points

Issue35 cf region

---

public/js/components/App.js
public/js/demo.js

Change 'writing' tone category name and id to 'language' tone category name and id.

[IN PROGRESS DO NOT MERGE] change 'writing' to 'language'

---

README.md
app.js
package.json
public/css/style.css
public/data/personal-email.txt
public/images/icons/code.svg
public/js/components/App.js
public/js/demo.js
views/index.ejs

[PENDING - DON'T MERGE] UI updates

---

public/js/components/App.js
public/js/components/helpers.js
public/js/demo.js

This fixes the linting errors in master

Fixes linting errors

---

public/js/components/App.js
public/js/demo.js

The float values were being compared as strings. 
As a result 5.0 value was being marked greater than 40.0

Fixed issue with emotion tone - likely, unlikely calculation

---

public/data/personal-email.txt

To go with new emotion release.

Minor edits to personal email sample

---

.gitignore
views/index.ejs

added feedback form

---

public/css/style.css
public/js/components/App.js
public/js/demo.js
views/index.ejs

added content for #1114 issue

---

public/data/customer-call.txt
public/data/personal-email.txt

We recently made some changes in service. Changing samples to show appropriate tones.

Data samples changed

---

public/css/style.css
public/js/components/App.js
public/js/demo.js

Added html to description of sentence tones.
Modified JS & CSS "Very Likely" for document tone items that are above .75

added text changes

---

README.md
manifest.yml

Update for the freemium releases

Update to use lite plan

---

.env.example
README.md
app.js
package-lock.json
package.json
public/js/analytics.js
public/js/demo.js
views/index.ejs

Related to https://github.ibm.com/Watson/developer-experience/issues/1840

Adding analytics

---

README.md

This is the simplest "Deploy to Bluemix Button" possible (a single line in your README.md) file.

Implement simple D2BM Button

---

README.md
public/data/personal-email.txt
public/data/tweets.txt
views/index.ejs

#113 
The introduction and input samples need to be updated to reflect the changes in the service.

Sample and description updates for Tone Analyzer Demo

---

package.json
public/data/tweets-fr.txt
public/js/demo.js
views/index.ejs

Added Tweets in French sample input. #112 
https://tone-analyzer-demo-r-fr-sample.mybluemix.net/

Added Tweets in French sample input

---

public/data/tweets-fr.txt

Modified french sample. #117 
https://tone-analyzer-demo-r-fr-sample.mybluemix.net/

Modified french sample.

---

public/css/style.css
public/data/review-fr.txt
public/data/tweets-fr.txt
public/js/demo.js
views/index.ejs

Allow choosing language for 'Your own text' input option. Update french input sample. #119

Allow choosing language for 'Your own text' input option. Update french input sample.

---

i18n/en.json
i18n/fr.json
public/css/style.css
views/index.ejs

This closes #130 
Demo hosted here: https://tone-analyzer-demo-gdpr-r.stage1.mybluemix.net/
**Still waiting for a response for availability for GDPR text in other languages for localization.** - No response yet. Will add later if needed.

Added gdpr text

---

README.md
package-lock.json
package.json
public/js/components/App.js
public/js/components/helpers.js
public/js/demo.js
server.js
test/integration/test.integration.express.js
views/index.ejs

Related to https://github.ibm.com/Watson/developer-experience/issues/4731

chore(npm): update dependencies, readme, tests

---

test/integration/integration.express.test.js
test/unit/express.test.js
views/index.ejs

adds the terms of use to the application

feat(Index): add terms of use
